# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-01-19 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20190111_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
