# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-01-19 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_partner_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='category',
            field=models.CharField(choices=[('ko', '한식'), ('jp', '일식'), ('cn', '중식'), ('wst', '양식')], default='ko', max_length=20),
        ),
    ]
