# Generated by Django 2.1.7 on 2019-03-14 02:24

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_auto_20190125_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='category',
            field=models.CharField(choices=[('ko', '한식'), ('jp', '일식'), ('cn', '중식'), ('wst', '양식')], default='ko', max_length=20, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to='partner/menu', verbose_name='대표이미지'),
        ),
    ]
